replicaCount: 1

image:
  repository: harbor.abstractolotl.de/abstractolotl/aznopoly-web
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
  - name: regcred

podAnnotations: {}

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: default-secured@kubernetescrd
    cert-manager.io/cluster-issuer: letsencrypt-production
  hosts:
    - host: aznopoly.abstractolotl.de
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: aznopoly.abstractolotl.de
      hosts:
        - aznopoly.abstractolotl.de

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

livenessProbe:
  httpGet:
    path: /
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 15
  timeoutSeconds: 30

readinessProbe:
  httpGet:
    path: /
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 15
  timeoutSeconds: 30